-- populate_caribou_population_unit.sql
delete from caribou_population_unit;
insert into caribou_population_unit (name, record_effective_date) values ('Atlin', now());
insert into caribou_population_unit (name, record_effective_date) values ('Calendar', now());
insert into caribou_population_unit (name, record_effective_date) values ('Carcross', now());
insert into caribou_population_unit (name, record_effective_date) values ('Chase', now());
insert into caribou_population_unit (name, record_effective_date) values ('Itcha-Ilgachuz', now());
insert into caribou_population_unit (name, record_effective_date) values ('Kennedy Siding', now());
insert into caribou_population_unit (name, record_effective_date) values ('Moberly', now());
insert into caribou_population_unit (name, record_effective_date) values ('Monashee', now());
insert into caribou_population_unit (name, record_effective_date) values ('Chinchaga', now());
insert into caribou_population_unit (name, record_effective_date) values ('Edziza', now());
insert into caribou_population_unit (name, record_effective_date) values ('Finlay', now());
insert into caribou_population_unit (name, record_effective_date) values ('Frog', now());
insert into caribou_population_unit (name, record_effective_date) values ('Gataga', now());
insert into caribou_population_unit (name, record_effective_date) values ('George Mountain', now());
insert into caribou_population_unit (name, record_effective_date) values ('Horseranch', now());
insert into caribou_population_unit (name, record_effective_date) values ('Level-Kawdy', now());
insert into caribou_population_unit (name, record_effective_date) values ('Liard Plateau', now());
insert into caribou_population_unit (name, record_effective_date) values ('Tweedsmuir', now());
insert into caribou_population_unit (name, record_effective_date) values ('Pink Mountain', now());
insert into caribou_population_unit (name, record_effective_date) values ('Barkerville', now());
insert into caribou_population_unit (name, record_effective_date) values ('Burnt Pine', now());
insert into caribou_population_unit (name, record_effective_date) values ('Central Rockies', now());
insert into caribou_population_unit (name, record_effective_date) values ('Central Selkirks', now());
insert into caribou_population_unit (name, record_effective_date) values ('Charlotte Alplands', now());
insert into caribou_population_unit (name, record_effective_date) values ('Columbia North', now());
insert into caribou_population_unit (name, record_effective_date) values ('Columbia South', now());
insert into caribou_population_unit (name, record_effective_date) values ('Frisby Boulder', now());
insert into caribou_population_unit (name, record_effective_date) values ('Graham', now());
insert into caribou_population_unit (name, record_effective_date) values ('Groundhog', now());
insert into caribou_population_unit (name, record_effective_date) values ('Little Rancheria', now());
insert into caribou_population_unit (name, record_effective_date) values ('Maxhamish', now());
insert into caribou_population_unit (name, record_effective_date) values ('Rabbit', now());
insert into caribou_population_unit (name, record_effective_date) values ('Snake-Sahtaneh', now());
insert into caribou_population_unit (name, record_effective_date) values ('Spatsizi', now());
insert into caribou_population_unit (name, record_effective_date) values ('Swan Lake', now());
insert into caribou_population_unit (name, record_effective_date) values ('Takla', now());
insert into caribou_population_unit (name, record_effective_date) values ('Thutade', now());
insert into caribou_population_unit (name, record_effective_date) values ('Tsenaglode', now());
insert into caribou_population_unit (name, record_effective_date) values ('Wolverine', now());
insert into caribou_population_unit (name, record_effective_date) values ('Westside Fort Nelson', now());
insert into caribou_population_unit (name, record_effective_date) values ('Muskwa', now());
insert into caribou_population_unit (name, record_effective_date) values ('Hart Ranges', now());
insert into caribou_population_unit (name, record_effective_date) values ('Narraway', now());
insert into caribou_population_unit (name, record_effective_date) values ('Narrow Lake', now());
insert into caribou_population_unit (name, record_effective_date) values ('North Cariboo', now());
insert into caribou_population_unit (name, record_effective_date) values ('Purcell Central', now());
insert into caribou_population_unit (name, record_effective_date) values ('Purcells South', now());
insert into caribou_population_unit (name, record_effective_date) values ('Quintette', now());
insert into caribou_population_unit (name, record_effective_date) values ('Rainbows', now());
insert into caribou_population_unit (name, record_effective_date) values ('Redrock-Prairie Creek', now());
insert into caribou_population_unit (name, record_effective_date) values ('South Selkirks', now());
insert into caribou_population_unit (name, record_effective_date) values ('Telkwa', now());
insert into caribou_population_unit (name, record_effective_date) values ('Wells Gray North', now());
insert into caribou_population_unit (name, record_effective_date) values ('Wells Gray South', now());
insert into caribou_population_unit (name, record_effective_date) values ('Scott', now());