kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAME
    value: restoration-tracker-db-setup
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Database setup image stream
      labels:
        shared: 'true'
      creationTimestamp: null
      generation: 0
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
